import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RecoilContextProvider from "@/lib/recoilContextProvider";
import Navbar from "@/components/NavBar";
import { Source_Sans_3 } from "next/font/google";


const sansFont = Source_Sans_3({
  weight: "500",
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sansFont.className} tracking-wide antialiased`}
      >
        <RecoilContextProvider>
          <Navbar />
          {children}
        </RecoilContextProvider>
      </body>
    </html>
  );
}
